baseURL: https://wsoares.netlify.app/
title: Walter Soares
theme: gokarna
languageCode: en
defaultContentLanguage: en
enableEmoji: yes
enableRobotsTXT: yes
pygmentsStyle: monokai
params:
  AvatarAltText: avatar
  ShowBackToTopButton: yes
  avatarSize: size-m
  avatarURL: /images/photo.jpg
  customHeadHTML: "    <!-- KaTeX -->\r\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css\"
    integrity=\"sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC\"
    crossorigin=\"anonymous\">\r\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js\"
    integrity=\"sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja\"
    crossorigin=\"anonymous\"></script>\r\n    <script defer src=\"https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js\"
    integrity=\"sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR\"
    crossorigin=\"anonymous\"></script>\r\n    <script>\r\n      document.addEventListener(\"DOMContentLoaded\",
    function() {\r\n        renderMathInElement(document.body, {\r\n          // customised
    options\r\n          // • auto-render specific keys, e.g.:\r\n          delimiters:
    [\r\n            {left: '$$', right: '$$', display: true},\r\n            {left:
    '$', right: '$', display: false},\r\n          ],\r\n          // • rendering
    keys, e.g.:\r\n          throwOnError : false\r\n        });\r\n      });\r\n
    \   </script>\r\n  "
  description: Analista e Cientista de Dados
  footer: Todos os direitos reservados.
  metaKeywords:
    - blog
    - gokarna
    - hugo
  socialIcons:
    - name: twitter
      url: https://twitter.com/w_soares
    - name: linkedin
      url: https://www.linkedin.com/in/walter-soares/
    - name: github
      url: https://github.com/wsoaresjr
    - name: email
      url: mailto:wsoares@live.com
    #- name: instagram
      #url: https://example.com
    #- name: twitch
      #url: https://example.com
    #- name: email
      #url: mailto:example@example.com
menu:
  main:
    - name: Home
      pre: <span data-feather='home'></span>
      url: /
      weight: 1
    - name: Posts
      pre: <span data-feather='book'></span>
      url: /posts/
      weight: 2
    - name: Projetos
      pre: <span data-feather='code'></span>
      url: /projects/
      weight: 3
    - name: Tags
      pre: <span data-feather='tag'></span>
      url: /tags/
      weight: 4
    #- identifier: github
      #pre: <span data-feather='github'></span>
      #url: https://github.com/526avijitgupta/gokarna
      #weight: 5
    - identifier: buymeacoffee
      pre: <span data-feather='coffee'></span>
      url: /
      weight: 6
    - identifier: rss
      pre: <span data-feather='rss'></span>
      url: /index.xml
      weight: 7
markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 1
